args: !!python/object:argparse.Namespace
  accelerator: ddp
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  automatic_optimization: null
  base_lr: 1.0e-05
  base_network_channels: 4
  batch_size: 1
  benchmark: true
  block_type: pre-activation
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  data_key: amplitudes
  dataset_path: /home/gpoloudenny/Projects/crystallography/data/mp20/amplitudes/normalized.h5
  default_root_dir: null
  deterministic: false
  distributed_backend: null
  enable_pl_optimizer: null
  extract_center_cylinder: true
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: 1
  gradient_clip_val: 0
  hkl_max_index: 10
  input_channels: 1
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  max_epochs: 100000
  max_steps: null
  metric: huber
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  n_bottleneck_blocks: 3
  n_downscales_per_bottleneck: 2
  n_mix: 2
  n_post_downscale_blocks: 0
  n_post_quantization_blocks: 0
  n_post_upscale_blocks: 0
  n_pre_quantization_blocks: 0
  num_embeddings: 256
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 16
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 0.5
  weights_save_path: null
  weights_summary: full
